[package]
name = "factorio-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
byteorder = "1.4.3"
indexmap = "1.9.3"
nom = "7.1.3"
thiserror = "1.0.40"
